black: true
check-xml: true
check-yaml: true
clang-format: false
flake8: true
format-xmllint: false
isort: true
# Enable mypy for type checking. See DM-44122.
mypy: false
ruff: false
towncrier: false
