version: "3.7"

services:

  producer:
    container_name: producer-local
    build:
      context: .
      dockerfile: Dockerfile-dev
      args:
        dev_cycle: ${dev_cycle}
    image: love-producer-image-mount
    volumes:
      - .:/usr/src/love
    stdin_open: true
    tty: true

  producer-deploy:
    container_name: producer
    build:
      context: .
      dockerfile: Dockerfile
      args:
        cycle: ${cycle}
    image: ts-dockerhub.lsst.org/love-producer:${cycle}
    volumes:
      - .:/usr/src/love
    stdin_open: true
    tty: true
