version: "3.7"

services:

  producer:
    container_name: producer-local
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: love-producer-image-mount
    volumes:
      - .:/usr/src/love
    command: "/usr/src/love/setup.sh"
    stdin_open: true
    tty: true

  tests:
    container_name: producer-tests
    image: producer-tests
    build:
      context: .
      dockerfile: Dockerfile
    command: "/usr/src/love/producer/producer/run-tests.sh"