ARG LSSTTS_DEV_VERSION=develop
FROM lsstts/develop-env:${LSSTTS_DEV_VERSION}

WORKDIR /usr/src/love/producer/love_csc
COPY producer/love_csc/requirements.txt ./requirements.txt
RUN source /opt/lsst/software/stack/loadLSST.bash && pip install -r ./requirements.txt
COPY producer ..
ENTRYPOINT ["/usr/src/love/producer/love_csc/.setup.sh"]