version: "3.7"

services:

  producer:
    container_name: love-producer-docs
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: love-producer-image-docs
    environment:
      - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
      - WEBSOCKET_HOST=${LOVE_PRODUCER_WEBSOCKET_HOST}
      - PROCESS_CONNECTION_PASS=${PROCESS_CONNECTION_PASS}
    volumes:
      - .:/usr/src/love
    command: "/usr/src/love/create_docs_in_docker.sh"
    network_mode: ${NETWORK_NAME}
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
