# This install file works with `pip install .`
# but not with `python setup.py install`.
import setuptools

scm_version_template = """# Generated by setuptools_scm
__all__ = ["__version__"]

__version__ = "{version}"
"""

setuptools.setup(
    name="love-producer",
    description="LSST Operators Visualization Environment (LOVE) producer.",
    use_scm_version={
        "write_to": "python/love/producer/version.py",
        "write_to_template": scm_version_template,
    },
    scripts=["bin/run_love_producer", "bin/run_love_csc"],
    package_dir={"": "python"},
    packages=setuptools.find_namespace_packages(where="python"),
    include_package_data=True,
    package_data={
        "": ["*.json"],
    },
    license="GPL",
    project_url={
        "Bug Tracker": "https://jira.lsstcorp.org/secure/Dashboard.jspa",
        "Source Code": "https://github.com/lsst-ts/LOVE-producer",
    },
)
