{% set data= load_setup_py_data() %}
package:
  name: love-producer
  version: {{ data.get('version') }}

source:
  path: ../

build:
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - run_love_producer = lsst.ts.love.producer:run_love_producer

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools
  run:
    - aiohttp
    - eventlet
    - gevent
    - greenlet
    - python
    - setuptools
    - setuptools_scm
    - six
    - ts-idl
    - ts-salobj
    - websocket-client
    - websockets
